version: '3.8'
services:
  back:
    image: ernestito62/bobapp-back
    container_name: bobapp-back
    ports:
      - "8080:8080"
  front:
    image: ernestito62/bobapp-front
    container_name: bobapp-front
    ports:
      - "4200:80"
    depends_on:
      - back