name: BobApp CI/CD

on:
  push:
    branches:
      - main
      - feat/github-actions
  pull_request:
    branches:
      - main

jobs:
  back:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run back-end tests
        run: mvn clean verify
        working-directory: ./back

      - name: Generate JaCoCo coverage report
        run: mvn jacoco:report
        working-directory: ./back

