name: BobApp CI/CD Pipeline
on:
  push:
    branches:
      - main
      - develop
      - 'feat/**'

jobs:
  ci-back:
    name: CI Back
    uses: ./.github/workflows/ci-back.yml
    secrets: inherit

  ci-front:
    name: CI Front
    uses: ./.github/workflows/ci-front.yml
    secrets: inherit

  deploy:
    name: Deploy to Docker
    needs:
      - ci-back
      - ci-front
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/deploy.yml
    secrets: inherit